#!/bin/sh
## run example GISTIC analysis

## output directory
echo --- creating output directory ---
basedir=`pwd`/gistic_results
mkdir -p $basedir 

echo --- running GISTIC ---
## input file definitions
segfile=`pwd`/variants_gatk_seg.txt
refgenefile=`pwd`/hg16.mat

## call script that sets MCR environment and calls GISTIC executable 
./gistic2 -b $basedir -seg $segfile -refgene $refgenefile  -genegistic 1 -smallmem 1 -broad 1 -brlen 0.5 -conf 0.90 -armpeel 1 -savegene 1 -gcm extreme

